{
  "CompileError": {
    "module": "test_break_continue_outside_loop.np",
    "errors": [
      {
        "message": "Cannot use break outside a loop",
        "line": 1
      },
      {
        "message": "Cannot use continue outside a loop",
        "line": 2
      }
    ]
  }
}